In [1]:
import pandas as pd
import re

In [2]:
medals = pd.read_csv('olympic_medals.csv')
hosts = pd.read_csv('olympic_hosts.csv')

In [3]:
medals

,discipline_title,slug_game,event_title,event_gender,medal_type,participant_type,participant_title,athlete_url,athlete_full_name,country_name,country_code,country_3_letter_code
0,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/stefania-cons...,Stefania CONSTANTINI,Italy,IT,ITA
1,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/amos-mosaner,Amos MOSANER,Italy,IT,ITA
2,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/kristin-skaslien,Kristin SKASLIEN,Norway,NO,NOR
3,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/magnus-nedreg...,Magnus NEDREGOTTEN,Norway,NO,NOR
4,Curling,beijing-2022,Mixed Doubles,Mixed,BRONZE,GameTeam,Sweden,https://olympics.com/en/athletes/almida-de-val,Almida DE VAL,Sweden,SE,SWE
...,...,...,...,...,...,...,...,...,...,...,...,...
21692,Weightlifting,athens-1896,heavyweight - one hand lift men,Men,SILVER,Athlete,NaN,https://olympics.com/en/athletes/viggo-jensen,Viggo JENSEN,Denmark,DK,DEN
21693,Weightlifting,athens-1896,heavyweight - one hand lift men,Men,BRONZE,Athlete,NaN,NaN,Alexandros Nikolopoulos,Greece,GR,GRE
21694,Weightlifting,athens-1896,heavyweight - two hand lift men,Men,GOLD,Athlete,NaN,https://olympics.com/en/athletes/viggo-jensen,Viggo JENSEN,Denmark,DK,DEN
21695,Weightlifting,athens-1896,heavyweight - two hand lift men,Men,SILVER,Athlete,NaN,https://olympics.com/en/athletes/launceston-el...,Launceston ELLIOT,Great Britain,GB,GBR
21696,Weightlifting,athens-1896,heavyweight - two hand lift men,Men,BRONZE,Athlete,NaN,https://olympics.com/en/athletes/sotirios-versis,Sotirios VERSIS,Greece,GR,GRE

In [4]:
medals['year'] = medals['slug_game'].str.extract(r'(\d{4})').astype(int)

In [5]:
medals['year']

0        2022
1        2022
2        2022
3        2022
4        2022
         ...
21692    1896
21693    1896
21694    1896
21695    1896
21696    1896
Name: year, Length: 21697, dtype: int64

In [6]:
hosts.head()

,game_slug,game_end_date,game_start_date,game_location,game_name,game_season,game_year
0,beijing-2022,2022-02-20T12:00:00Z,2022-02-04T15:00:00Z,China,Beijing 2022,Winter,2022
1,tokyo-2020,2021-08-08T14:00:00Z,2021-07-23T11:00:00Z,Japan,Tokyo 2020,Summer,2020
2,pyeongchang-2018,2018-02-25T08:00:00Z,2018-02-08T23:00:00Z,Republic of Korea,PyeongChang 2018,Winter,2018
3,rio-2016,2016-08-21T21:00:00Z,2016-08-05T12:00:00Z,Brazil,Rio 2016,Summer,2016
4,sochi-2014,2014-02-23T16:00:00Z,2014-02-07T04:00:00Z,Russian Federation,Sochi 2014,Winter,2014

In [7]:
hosts_slim = hosts[['game_slug', 'game_season', 'game_year']].copy()

In [8]:
hosts_slim.head()

          game_slug game_season  game_year
0      beijing-2022      Winter       2022
1        tokyo-2020      Summer       2020
2  pyeongchang-2018      Winter       2018
3          rio-2016      Summer       2016
4        sochi-2014      Winter       2014

In [9]:
medals = medals.merge(hosts_slim, left_on = 'slug_game', right_on = 'game_slug', how='left' )

In [10]:
medals.head()

,discipline_title,slug_game,event_title,event_gender,medal_type,participant_type,participant_title,athlete_url,athlete_full_name,country_name,country_code,country_3_letter_code,year,game_slug,game_season,game_year
0,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/stefania-cons...,Stefania CONSTANTINI,Italy,IT,ITA,2022,beijing-2022,Winter,2022
1,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/amos-mosaner,Amos MOSANER,Italy,IT,ITA,2022,beijing-2022,Winter,2022
2,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/kristin-skaslien,Kristin SKASLIEN,Norway,NO,NOR,2022,beijing-2022,Winter,2022
3,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/magnus-nedreg...,Magnus NEDREGOTTEN,Norway,NO,NOR,2022,beijing-2022,Winter,2022
4,Curling,beijing-2022,Mixed Doubles,Mixed,BRONZE,GameTeam,Sweden,https://olympics.com/en/athletes/almida-de-val,Almida DE VAL,Sweden,SE,SWE,2022,beijing-2022,Winter,2022

In [11]:
medals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21697 entries, 0 to 21696
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   discipline_title       21697 non-null  object
 1   slug_game              21697 non-null  object
 2   event_title            21697 non-null  object
 3   event_gender           21697 non-null  object
 4   medal_type             21697 non-null  object
 5   participant_type       21697 non-null  object
 6   participant_title      6584 non-null   object
 7   athlete_url            17027 non-null  object
 8   athlete_full_name      18073 non-null  object
 9   country_name           21697 non-null  object
 10  country_code           20195 non-null  object
 11  country_3_letter_code  21697 non-null  object
 12  year                   21697 non-null  int64
 13  game_slug              21697 non-null  object
 14  game_season            21697 non-null  object
 15  game_year              21697 non-null  int64
dtypes: int64(2), object(14)
memory usage: 2.6+ MB

In [12]:
hosts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   game_slug        53 non-null     object
 1   game_end_date    53 non-null     object
 2   game_start_date  53 non-null     object
 3   game_location    53 non-null     object
 4   game_name        53 non-null     object
 5   game_season      53 non-null     object
 6   game_year        53 non-null     int64
dtypes: int64(1), object(6)
memory usage: 3.0+ KB

In [13]:
print('Seasons in data:', medals['game_season'].unique())
print('Total rows:', len(medals))

Seasons in data: ['Winter' 'Summer']
Total rows: 21697

In [ ]:
#  Count medals per nation per edition per season
# Each row in olympic_medals.csv = one medal awarded grouping and counting rows gives medal count per group
medal_counts = medals.groupby([ 'country_3_letter_code',
    'country_name','year', 'game_season']).size().reset_index(name='medal_count')

In [15]:
medal_counts

,country_3_letter_code,country_name,year,game_season,medal_count
0,AFG,Afghanistan,2008,Summer,1
1,AFG,Afghanistan,2012,Summer,1
2,AHO,Netherlands Antilles,1988,Summer,1
3,ALG,Algeria,1984,Summer,2
4,ALG,Algeria,1992,Summer,2
...,...,...,...,...,...
1774,ZAM,Zambia,1984,Summer,1
1775,ZAM,Zambia,1996,Summer,1
1776,ZIM,Zimbabwe,1980,Summer,1
1777,ZIM,Zimbabwe,2004,Summer,3
1778,ZIM,Zimbabwe,2008,Summer,4

In [16]:
# Compute total medals per edition per season
# Normalisation denominator: all medals awarded in that year + season this removes bias caused by the programme growing over time
# Summer grew from 43 events (1896) to 300+ events (2020)
# Without normalisation later nations appear stronger simply due to more medals
edition_totals = (medal_counts.groupby(['year','game_season'])['medal_count'].sum().reset_index(name='total_medals'))

In [17]:
edition_totals

    year game_season  total_medals
0   1896      Summer           126
1   1900      Summer           292
2   1904      Summer           290
3   1908      Summer           343
4   1912      Summer           323
5   1920      Summer           457
6   1924      Summer           395
7   1924      Winter            52
8   1928      Summer           333
9   1928      Winter            44
10  1932      Summer           358
11  1932      Winter            48
12  1936      Summer           388
13  1936      Winter            57
14  1948      Summer           438
15  1948      Winter            74
16  1952      Summer           465
17  1952      Winter            73
18  1956      Summer           478
19  1956      Winter            78
20  1960      Summer           484
21  1960      Winter            84
22  1964      Summer           528
23  1964      Winter           114
24  1968      Summer           551
25  1968      Winter           115
26  1972      Summer           630
27  1972      Winter           114
28  1976      Summer           652
29  1976      Winter           123
30  1980      Summer           670
31  1980      Winter           127
32  1984      Summer           730
33  1984      Winter           129
34  1988      Summer           797
35  1988      Winter           150
36  1992      Summer           887
37  1992      Winter           183
38  1994      Winter           195
39  1996      Summer           917
40  1998      Winter           217
41  2000      Summer          1023
42  2002      Winter           249
43  2004      Summer          1022
44  2006      Winter           273
45  2008      Summer          1047
46  2010      Winter           279
47  2012      Summer          1044
48  2014      Winter           314
49  2016      Summer          1063
50  2018      Winter           331
51  2020      Summer          1188
52  2022      Winter           355

In [18]:
# Merge totals and compute medal share 
# medal_share = (nation medals / edition total) * 100
medal_counts = medal_counts.merge(edition_totals, on=['year','game_season'])

medal_counts['medal_share'] = (medal_counts['medal_count'] / medal_counts['total_medals'] * 100).round(2)

In [19]:
medal_counts

,country_3_letter_code,country_name,year,game_season,medal_count,total_medals,medal_share
0,AFG,Afghanistan,2008,Summer,1,1047,0.10
1,AFG,Afghanistan,2012,Summer,1,1044,0.10
2,AHO,Netherlands Antilles,1988,Summer,1,797,0.13
3,ALG,Algeria,1984,Summer,2,730,0.27
4,ALG,Algeria,1992,Summer,2,887,0.23
...,...,...,...,...,...,...,...
1774,ZAM,Zambia,1984,Summer,1,730,0.14
1775,ZAM,Zambia,1996,Summer,1,917,0.11
1776,ZIM,Zimbabwe,1980,Summer,1,670,0.15
1777,ZIM,Zimbabwe,2004,Summer,3,1022,0.29
1778,ZIM,Zimbabwe,2008,Summer,4,1047,0.38

In [20]:
# Remove sparse nations - Nations with fewer than 5 medal-winning editions in a season
# are removed to avoid misleading single-point spikes in the line chart
editions_count = (medal_counts.groupby(['country_3_letter_code','game_season'])['year'].nunique().reset_index(name='edition_count'))

active = editions_count[editions_count['edition_count'] >= 5]

medal_counts = medal_counts.merge(
    active[['country_3_letter_code','game_season']],
    on=['country_3_letter_code','game_season'],
    how='inner'
)

In [21]:
medal_counts.to_csv('medals_clean.csv', index=False)

print(f'Exported {len(medal_counts)} rows')

print(f'Nations (Summer): {medal_counts[medal_counts.game_season=="Summer"].country_3_letter_code.nunique()}')
print(f'Nations (Winter): {medal_counts[medal_counts.game_season=="Winter"].country_3_letter_code.nunique()}')
print(medal_counts.head())

Exported 1609 rows
Nations (Summer): 84
Nations (Winter): 32
  country_3_letter_code country_name  year game_season  medal_count  \
0                   ALG      Algeria  1984      Summer            2
1                   ALG      Algeria  1992      Summer            2
2                   ALG      Algeria  1996      Summer            3
3                   ALG      Algeria  2000      Summer            5
4                   ALG      Algeria  2008      Summer            2

   total_medals  medal_share
0           730         0.27
1           887         0.23
2           917         0.33
3          1023         0.49
4          1047         0.19